services:
  backend:
    container_name: portofino-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env_secret
    volumes:
      - reports-data:/tmp/reports
    networks:
      - portofino_net
    depends_on:
      - postgres
      - redis
      - kafka
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 20
      start_period: 80s

  frontend:
    container_name: portofino-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    networks:
      - portofino_net
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: always

  postgres:
    container_name: portofino-postgres
    image: postgres:16
    env_file:
      - .env
      - .env_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portofino_net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    container_name: portofino-redis
    image: redis:7-alpine
    networks:
      - portofino_net
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis_exporter:
    container_name: portofino-redis-exporter
    image: oliver006/redis_exporter:latest
    networks:
      - portofino_net
    depends_on:
      - redis
    ports:
      - "9121:9121"
    command:
      - '--redis.addr=redis:6379'

  kafka:
    container_name: portofino-kafka
    image: confluentinc/cp-kafka:7.7.0
    init: true
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "simulation_requests:1:1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - portofino_net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - portofino_net
    ports:
      - "22181:2181"
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    container_name: portofino-kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME=PortoFinoCluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_READONLY=false
    networks:
      - portofino_net
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8085:8080"
    restart: always

  kafka_exporter:
    container_name: portofino-kafka-exporter
    image: danielqsj/kafka-exporter:latest
    networks:
      - portofino_net
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9308:9308"
    command:
      - --kafka.server=kafka:9092
      - --web.listen-address=:9308
      - --web.telemetry-path=/metrics
    pull_policy: never
    restart: always

  worker:
    container_name: portofino-worker
    build:
      context: ./backend
    env_file:
      - .env
      - .env_secret
    volumes:
      - reports-data:/tmp/reports
    networks:
      - portofino_net
    depends_on:
      - backend
      - redis
      - kafka
    command: celery -A services.worker.celery_app worker --pool=solo -Q workers_queue -c 1 -l info
    restart: always
    healthcheck:
      test:  ["CMD-SHELL", "celery -A services.worker.celery_app inspect ping"]
      interval: 20s
      timeout: 10s
      retries: 5

  celery_beat:
    container_name: portofino-celery-beat
    build:
      context: ./backend
    env_file:
      - .env
      - .env_secret
    networks:
      - portofino_net
    depends_on:
      - backend
      - worker
      - kafka
      - redis
    command: celery -A services.worker.celery_app beat --loglevel=info
    restart: always

  flower:
    container_name: portofino-flower
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - portofino_net
    env_file:
      - .env
      - .env_secret
    depends_on:
      - redis
      - worker
    ports:
      - "5555:5555"
      - "5556:5556"
    command: celery -A services.worker.celery_app:celery_app flower --port=5555 --prometheus-port=5556
    restart: always

  prometheus:
    container_name: portofino-prometheus
    image: prom/prometheus:latest
    networks:
      - portofino_net
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend
      - worker
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: portofino-grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./monitoring/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped

  node_exporter:
    container_name: portofino-node-exporter
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
    networks:
      - portofino_net
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: "host"


networks:
  portofino_net:


volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  reports-data: